
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 29 22:44:01 CST 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OR_LOG = 47;
  public static final int LESS_TE = 51;
  public static final int CHAR_TYPE = 14;
  public static final int POW = 45;
  public static final int LIT_EXPONENTE = 8;
  public static final int LIT_FRACCION = 7;
  public static final int EMPTY = 27;
  public static final int UMINUS = 41;
  public static final int CASE = 21;
  public static final int L_PAREN = 33;
  public static final int R_PAREN = 34;
  public static final int INT = 11;
  public static final int GREATER_TE = 50;
  public static final int EQUAL_OP = 52;
  public static final int MINUS = 40;
  public static final int GREATER_T = 48;
  public static final int COMMA = 37;
  public static final int BOOL = 13;
  public static final int SEPARATOR = 30;
  public static final int DIV = 43;
  public static final int PLUS = 39;
  public static final int L_ARRAY = 35;
  public static final int ASSIGN = 29;
  public static final int MAIN = 28;
  public static final int IF = 16;
  public static final int AND_LOG = 46;
  public static final int ID = 2;
  public static final int R_ARRAY = 36;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int STRING_TYPE = 15;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int L_BLOCK = 31;
  public static final int LIT_STRING = 3;
  public static final int R_BLOCK = 32;
  public static final int MOD = 44;
  public static final int LIT_CHAR = 4;
  public static final int CIN = 23;
  public static final int BREAK = 26;
  public static final int SWITCH = 20;
  public static final int TIMES = 42;
  public static final int LIT_FLOTANTE = 6;
  public static final int ELSE = 17;
  public static final int N_EQUAL = 53;
  public static final int COUT = 24;
  public static final int WHILE = 19;
  public static final int DEFAULT = 22;
  public static final int FLOAT = 12;
  public static final int LIT_ENTERO = 5;
  public static final int END_EXPR = 38;
  public static final int FALSE = 10;
  public static final int LESS_T = 49;
  public static final int DO = 18;
}

